/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Funcoes.TaskSegmentation;
import com.sun.javafx.scene.control.SelectedCellsMap;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.List;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ademir
 */
public class Main_UI extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Main_UI
     */
    public Main_UI() {
        initComponents();
        setSize( 600, 400);  
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_buttons = new javax.swing.JPanel();
        btSegmentar_mdUI = new javax.swing.JButton();
        btSair_mdUI = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1_buttons.setLayout(new java.awt.GridLayout(1, 2));

        btSegmentar_mdUI.setText("Segmentar/Modular");
        btSegmentar_mdUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSegmentar_mdUIActionPerformed(evt);
            }
        });
        jPanel1_buttons.add(btSegmentar_mdUI);

        btSair_mdUI.setText("Sair");
        btSair_mdUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSair_mdUIActionPerformed(evt);
            }
        });
        jPanel1_buttons.add(btSair_mdUI);

        getContentPane().add(jPanel1_buttons, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sai do programa
     * @param evt 
     */
    private void btSair_mdUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSair_mdUIActionPerformed
        dispose();
    }//GEN-LAST:event_btSair_mdUIActionPerformed
    
    /**
     * Chama o frame do botão slecionado
     * @param evt 
     */
    private void btSegmentar_mdUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSegmentar_mdUIActionPerformed
        ModuleSegmantation_UI mdSeg = new ModuleSegmantation_UI(this, true);
        mdSeg.setTitle("Segmentacao");
        mdSeg.setLocationRelativeTo(null);
        mdSeg.setResizable(false);
        mdSeg.setVisible(true);
    }//GEN-LAST:event_btSegmentar_mdUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        
        String lookAndFeel = UIManager.getSystemLookAndFeelClassName(); // pega aparencia do SO  
        UIManager.setLookAndFeel(lookAndFeel);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_UI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair_mdUI;
    private javax.swing.JButton btSegmentar_mdUI;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1_buttons;
    // End of variables declaration//GEN-END:variables
}

