/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ademir
 */
public class Main_UI extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Main_UI
     */
    public Main_UI() {
        initComponents();
        setSize( 320, 240);  
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_buttons = new javax.swing.JPanel();
        btSegmentar_mdUI = new javax.swing.JButton();
        btSair_mdUI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        jPanel1_buttons.setLayout(new java.awt.GridLayout(1, 2));

        btSegmentar_mdUI.setText("Start");
        btSegmentar_mdUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSegmentar_mdUIActionPerformed(evt);
            }
        });
        jPanel1_buttons.add(btSegmentar_mdUI);

        getContentPane().add(jPanel1_buttons);

        btSair_mdUI.setText("Sair");
        btSair_mdUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSair_mdUIActionPerformed(evt);
            }
        });
        getContentPane().add(btSair_mdUI);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sai do programa
     * @param evt 
     */
    private void btSair_mdUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSair_mdUIActionPerformed
        dispose();
    }//GEN-LAST:event_btSair_mdUIActionPerformed
    
    /**
     * Chama o frame do botão slecionado
     * @param evt 
     */
    private void btSegmentar_mdUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSegmentar_mdUIActionPerformed
        ModuleSegmantation_UI mdSeg = new ModuleSegmantation_UI(this, true);
        
        mdSeg.setTitle("Smart Parking");
        mdSeg.setLocationRelativeTo(null);
        mdSeg.setResizable(false);
        //mdSeg.setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds()); 
        mdSeg.setVisible(true);
    }//GEN-LAST:event_btSegmentar_mdUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        
        String lookAndFeel = UIManager.getSystemLookAndFeelClassName(); // pega aparencia do SO  
        UIManager.setLookAndFeel(lookAndFeel);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_UI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair_mdUI;
    private javax.swing.JButton btSegmentar_mdUI;
    private javax.swing.JPanel jPanel1_buttons;
    // End of variables declaration//GEN-END:variables
}

